c-koi/gmic-qt

src/HeadlessProcessor.cpp
Add a missing include: 
src/HeadlessProcessor.cpp: In member function ‘void HeadlessProcessor::onProcessingFinished()’:
src/HeadlessProcessor.cpp:184:14: error: invalid use of incomplete type ‘class QDebug’
qWarning() << "Error:" << errorMessage;
^
In file included from /home/boud/dev/deps/include/QtCore/qglobal.h:1106:0,
from /home/boud/dev/deps/include/QtCore/qtimer.h:37,
from /home/boud/dev/deps/include/QtCore/QTimer:1,
from include/HeadlessProcessor.h:29,
from src/HeadlessProcessor.cpp:25:
/home/boud/dev/deps/include/QtCore/qlogging.h:51:7: error: forward declaration of ‘class QDebug’
class QDebug;
^
Makefile:9534: recipe for target '.obj/HeadlessProcessor.o' failed
make: *** [.obj/HeadlessProcessor.o] Error 1
=> Fix build error

CMakeLists.txt, cmake/modules/COPYING-CMAKE-SCRIPTS, cmake/modules/FindCairo.cmake, cmake/modules/FindFFTW3.cmake, cmake/modules/FindGimp2.cmake, cmake/modules/LibFindMacros.cmake
This build system can build gmic_qt (gimp, krita and host) on Windows (tested with mingw-64), Linux (gcc 4.8.5) and OSX (clang, 10.9 sdk), if the dependencies are present. 
Note: it's not perfect yet, I still need to figure out why cmake on OSX doesn't set the rpath correctly. It's possible that this cannot be done from cmake and must be done in a deploy script.
The following CMake variables can be used:
GMIC_QT_HOST = {krita|gimp|none}
GMIC_PATH: the path to the gmic checkout or release
PRELEASE: to indicate that this isn't a final release
=> Create a CMake-based build system

CMakeLists.txt
Use FindX11.cmake's ${X11_LIBRARIES} and not 'X11'.
https://cmake.org/cmake/help/v3.9/module/FindX11.html
=> Use FindX11.cmake

cmake/modules/FindFFTW3.cmake
Due to change to use fftw3's CMake build system instead of prebuilt binaries.
CC: @boudewijnrempt
=> Fix finding fftw3 on Windows with new Krita setup

CMakeLists.txt
... for reading the CImg and g'mic versions, so that it works on
Windows again.
CC: @boudewijnrempt
=> Use CMake file(STRINGS ...) instead of grep

gmic_qt.pro
Changes in the CImg Library (https://github.com/dtschump/CImg/commit/913065c6d61d0faeed895498e1c611b359a46bca) makes '-Ofast' a working optimization flag for compiling G'MIC.
=> Enable 'Ofast' optimizations.

CMakeLists.txt
Without setting property on the files, it was trying to find the
generated files on the root of the repository at install time.
After building gmic-qt and running `make install` (which doesn't seem to do much anyway!), I had this error:
```
$ make install
[  1%] Automatic MOC for target gmic_gimp_qt
[  1%] Built target gmic_gimp_qt_autogen
[100%] Built target gmic_gimp_qt
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:49 (file):
file INSTALL cannot find "/home/jehan/dev/build/gmic-qt/cs.qm".
make: *** [Makefile:118: install] Error 1
```
It seems that it expects the `qm` files to be at the root. I added some property to the file list to make it end without error (as inspired by [this](https://stackoverflow.com/questions/44782914/cmake-qt5-add-t …
=> Fix translation files path.

src/gmic_qt.cpp
The full path to the plug-in executable is
determined using the _NSGetExecutablePath() function.
The GMIC/plugins/ sub-folder is then added to the
QT_PLUGIN_PATH environment variable, so that Qt plugins
are searched relative to the emplacement of the
gmic_gimp_qt executable
=> Detect full plug-in path under MacOS

src/Host/PaintDotNet/host_paintdotnet.cpp
Use spaces instead of tabs for indentation and remove some extra white-space.
=> Minor cleanup in the Paint.NET host plugin

CMakeLists.txt, cmake/modules/FindFFTW3.cmake
Tested under Linux 64/32 bits, Windows 64/32 bits, and MacOS.
Note : the explicit hard-coded linking with fftw3_thread is now removed, as the path to this lib is now found at configuration stage.
=> remove previous cmake option to disable fftw3 support and fix linking stage with fftw3_thread under MacOS

CMakeLists.txt
We have to call pkg-config directly, since CMake’s pkg-config support is missing variable overriding:
https://gitlab.kitware.com/cmake/cmake/issues/19632
Variable overriding is required for obtaining proper installation paths:
https://www.bassi.io/articles/2018/03/15/pkg-config-and-paths/
=> build: Install GIMP plug-in to a correct directory

.github/FUNDING.yml
Please check the sponsorship checkbox in the repository settings.
Already applied on dstchump/gmic and myselfhimself/gmic-py
=> proposing github sponsor button on home page

CMakeLists.txt
Cf. our discussion on Twitter. This is the only change I had to do on the build system to be able to cross-build G'MIC for Windows.
There is another issue with the `CMAKE_AUTOMOC` tool but for now I could at least make the build work with Wine and binfmt_misc, which worked fine anyway. Eventually though if I can understand what `moc` does, it would be better to run a native binary at build time.
------------------------------------------------------------------------------------------
Hardcoding `pkg-config` will work only for native builds. If you want to
cross-compile, you need to search for the appropriate tools, which is
what FindPkgConfig module does. Then you can use PKG_CONFIG_EXECUTABLE
variable which will be set according to your toolchain rules.
Also old-style binary config …
=> CMakeLists: don't hardcode pkg-config and don't use gimptool anymore.

src/FilterSyncRunner.cpp, src/FilterThread.cpp
I had to make some slight modifications to the definition of the `gmic()` constructor in `gmic.h` , due to default template value not supported for functions, in MSVC2012.
The patch here fixes compilation issues of G'MIC-Qt regarding these changes.
=> Fix compilation issues with the latest G'MIC API changes.

CMakeLists.txt, src/Host/Gimp/host_gimp.cpp
=> gimp: Add experimental support for GIMP 3

src/Host/Gimp/host_gimp.cpp
For GIMP 2.99.6, the names of some symbols have changed in libgimp: https://gitlab.gnome.org/GNOME/gimp/-/blob/8b39b92acf1aad926ef61ffc0bbdd3dc68850604/NEWS#L140
This brings it in line but should keep backwards compatibility with GIMP 2 and prior 2.99.x releases. I haven't got a chance to test with those yet, so please test fully before merging.
=> gimp: Update for changed plugin API in gimp 2.99.6

src/Host/Gimp/host_gimp.cpp
Commit 2262774 took care of the GmicQt API change for "gimp" host only
(i.e. the GIMP 2.x variant), not for the gimp3 GMIC_QT_HOST.
It looks like GmicQt API changed happened between #112 being opened and merged. So it was still using the old API on this codepath. This fixes the gimp3 version of G'MIC-Qt build (tested locally).
=> src: port the gimp3 host to the new G'MIC-Qt API.

src/Host/Gimp/host_gimp.cpp
Each of the active layer ID comparisons was failing to compile for me:
error: ordered comparison of pointer with integer zero (‘GimpLayer*’ and ‘int’)
If the comparison were allowed, it’d always be true, pointers being unsigned. But the compiler isn’t liking it.
Comparing with _GIMP_NULL_LAYER, I presume that the `activeLayerID >= 0` comparisons need to become `activeLayerID != NULL`.
No idea if `activeLayerID != _GIMP_NULL_LAYER` would be acceptable or not; dunno if old GIMP did anything with -2, -3, *&c.* or if -1 was the only special value. Without that special knowledge, I figure that the macro I’ve added is probably safer.
I emphasise that as I submit this patch I do not know if it’s correct. All I do know is that with the patch it *compiles*, and trivial functionality seems to work.
=> Fix gimp3 building

src/Host/8bf/host_8bf.cpp
=> Remove an unused variable in CopyTileToGmicImage16Planar

CMakeLists.txt, cmake/modules/FindFFTW3.cmake, src/FilterParameters/FloatParameter.cpp, src/FilterParameters/IntParameter.cpp, src/FilterParameters/PointParameter.cpp, src/FilterSelector/FiltersPresenter.cpp, src/HeadlessProcessor.cpp, src/MainWindow.cpp, src/Utils.cpp
👋 
This PR upstreams the changes I did as part of the plugin port for Krita. The changes are:
- Fixed unary boolean operators (`not` -> `!`), making G'MIC-Qt compatible with MSVC
- Added LTO support for MSVC
- Added Android detection and support; with these adjustments, G'MIC can be built and run successfully (provided a host is compatible)
- Finally, I fixed FFTW Threads detection and usage on Windows
=> Add MSVC compatibility and other bits

gmic_qt.pro
One of the last G'MIC filters (`Rendering / Generate Random Portrait`) requires G'MIC-Qt to be able to load JPEG image data from the network. Currently, G'MIC-Qt is not compiled with the libjpeg support enabled.
This PR enables a new dependency to `libjpeg` by default.
Note that a similar modification has to be done for the file `CMakeLists.txt`, but I don't know how to do it properly :)
=> File 'gmic_qt.pro': Add dependency to 'libjpeg' by default.

src/FilterSyncRunner.cpp, src/FilterThread.cpp
Finally, to be coherent with how other variable names are defined by the plug-in (`_preview_width`, ...) , `_gmic_qt_persistent` should be indeed renamed to `_persistent`.
=> Rename '_gmic_qt_persistent' to '_persistent'.

src/FilterParameters/MultilineTextParameterWidget.h
👋 
Just a small nitpick I noticed during a Clang build.
=> Fix missing override

CMakeLists.txt, gmic_qt.pro, src/Host/8bf/host_8bf.cpp
The 32-bits-per-channel output of the 8bf filter plug-in does not always match GIMP.
This is probably due to differences in how GIMP and the various 8bf plug-in hosts display 32-bits-per-channel image data.
Added color management for the G'MIC-Qt preview, this adds a `lcms2` dependency when building the 8bf host.
G'MIC-Qt will attempt to retrieve the color profile for the display that G'MIC-Qt is using when the first call to `applyColorProfile` is made, if that is unsuccessful the color profile of the primary display will be used.
The display color profile will not be refreshed if the user moves the G'MIC-Qt UI to a different display within the same session.
=> [8bf] Add support for color managment and 32-bit floating point image data

CMakeLists.txt
PR c-koi/gmic-qt#172 is correct in that it is no longer possible to build without `-Dgmic_core`, due to G'MIC-Qt relying in now-private implementation details of G'MIC; namely, the extensions made in gmic.cpp to CImg.
However, the solution chosen has significant shortcomings:
1. It blindly assumes that the consumed library has been built by a GCC-compatible compiler. This is easily inferred from the lack of symbol exports in {CImg,gmic}.{h,cpp}.
2. It makes no provision for the exported library type; G'MIC can be built statically or dynamically.
3. In Windows, when built with MSVC, the kind of symbol export that gmic_core implies is only available with a static libgmic.
To fix this, this commit augments G'MIC-Qt's `ENABLE_DYNAMIC_LINKING` handling with target detection code for the above …
=> CMake: actually fix ENABLE_SYSTEM_GMIC

CMakeLists.txt
These were changed in eb5e2ad49 but it's not entirely clear why
The changed paths for the Qt forms aren't their real location, and it seems all of the host code was added for the default build, even though only the source files for the given `GMIC_QT_HOST` are needed and are conditionally added further down in the CMakeLists
I needed both of the commits in this PR for the CMake build to work for me (otherwise it errors out about UI form headers not being found and doesn't build with Qt5 because the 8bf host requires Qt6)
Am I missing anything or was this stuff just changed by mistake?
Thank you!
=> Fix CMake build with 3.2.2

gmic_qt.pro
Actually, handle all non-macOS Unixes the same way as Linux.
I think that's a safer default; possibly the 'message' should be updated as well but I'm not sure to what exactly.
Exclude macOS because one usually wants to avoid X11 there.
=> Fix build on NetBSD.

src/Host/Gimp/host_gimp.cpp
The plugin run function now receives a GimpProcedureConfig object since 2.99.19, instead of a GimpValueArray. Parameters for the plugin are named GObject properties on this config object which can be fetched with g_object_get.
Fixes: https://github.com/c-koi/gmic-qt/issues/207
Please note that I have **only** compile tested this currently. I **HAVE NOT** done functional testing. 
I developed this patch by looking at the changes done for GIMP's own wavelet plugin and doing the equivalent eg https://gitlab.gnome.org/GNOME/gimp/-/commit/c034c383c3c3b22c9b5012ddbba29225ed60eb0b
=> Host/Gimp: convert to new GimpProcedureConfig APIs
